version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./db-initialization-scripts/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    ports:
      - "5432:5432"
    networks:
      - data_platform_demo
    restart: unless-stopped

  mongodb_container:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    networks:
      - data_platform_demo
    volumes:
      - mongodb_data_container:/data/mongodb
      - ./db-initialization-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  presto:
    build:
      context: ./config
    image: ahanaio/prestodb-sandbox
    container_name: presto
    volumes:
      - presto:/usr/share/presto/data
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - data_platform_demo

networks:
  data_platform_demo:
    driver: bridge

volumes:
  postgres:
  mongodb_data_container:
  presto: